name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Aquí puedes agregar pasos adicionales para construir tu aplicación, por ejemplo, si usas npm:
      # - name: Install dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      # Agregar aquí los comandos necesarios para desplegar tu aplicación. Por ejemplo, si usas GitHub Pages:
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GH_PAGES }}